URL = ' https://www.metric-conversions.org/'
CELSIUS_TEXT = 'Celsius'
FAHRENHEIT_TEXT = 'Fahrenheit'
INPUT_Values = '5'
METERS_TEXT = 'Meters'
FEETS_TEXT = 'Feets'
OUNCES_TEXT = 'Ounces'
GRAMS_TEXT = 'Grams'
ANSWER = 'answer'

CONVERT_FROM_FIELD = 'queryFrom'
CONVERT_TO_FIELD = 'queryTo'
VALUES_FIELD = 'argument'
CONVERT_BUTTON = '//*[@id="results"]/ol/li[1]/div/a[2]'